CREATE TABLE `test1`(
	`id` INT not NULL DEFAULT 0,
	`name` VARCHAR(1) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT null,
PRIMARY KEY(`id`)
);

CREATE TABLE `test2`(
	`id` INT not NULL DEFAULT 0,
	`name` VARCHAR(1) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT null,
PRIMARY KEY(`id`)
)